name: Build and push image to Amazon ECR

on:
  push:
    branches:
      - feature_actions
  workflow_dispatch:

jobs:
  verification-and-build:
    runs-on: ubuntu-latest
    env:
      ecr_repository: fluentd-demo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Verification
        run: ./gradlew check
      - name: Build
        run: ./gradlew build -x test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: actionsSession
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setting environment variables
        run: |
          echo "image_tag=$(echo ${{ github.sha }} | head -c 8)" >> $GITHUB_ENV
          echo "ecr_registry=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
      - name: Building Docker images
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t ${ecr_registry}/${ecr_repository}:${image_tag} -t ${ecr_registry}/${ecr_repository}:latest .
#      - name: push image to Amazon ECR
#          docker tag ${ecr_repository}:${IMAGE_TAG} ${ECR_REGISTRY}/${ecr_repository}:${IMAGE_TAG}
#          docker tag ${ecr_repository}:${IMAGE_TAG} ${ECR_REGISTRY}/${ecr_repository}:latest
#      - name: push image to Amazon ECR
#        run: |
#          docker push ${ecr_registry}/${ecr_repository}:$image_tag
#          docker push ${ecr_registry}/${ecr_repository}:latest
